paths:
  output_dir: ../../results/tsne_encoder
  encoder_checkpoint: ../../checkpoints/ts_encoder_20251126_1750_ep10/time_series_best.pt
  projection_checkpoint: ../../checkpoints/ts_encoder_20251126_1750_ep10/time_series_projection_best.pt

  visual_encoder_checkpoint: ../../checkpoints/ts_encoder_20251126_1750_ep10/visual_encoder_best.pt
  visual_projection_checkpoint: ../../checkpoints/ts_encoder_20251126_1750_ep10/visual_projection_best.pt

tsne:
  samples_per_dataset: 1000
  perplexity: 35.0
  learning_rate: 200.0
  n_iter: 1000
  device: auto
  seed: 42
  show: false

data:
  # Root directory for ICML datasets
  data_dir: ../../ICML_datasets
  # ICML dataset filenames (keeping file extensions)
  dataset_names:
    - ETTm2.csv
    - PEMS04.npz
    - weather.csv
    - exchange_rate.csv
    - electricity.csv
    - solar_AL.txt
  dataset_name:
  filename:
  batch_size: 512
  val_batch_size: 512
  num_workers: 4
  split: train